### ISSUE TITLE
Create a UI prototype of the application

### ISSUE THREAD

**Issue by VriaA** [VriaA/hs-ai-customer-support#1]
###  Details
- [x] Design the prototype using Figma.
- [x] Define the color palette and fonts to be used in the application.
- [x] Ensure the design is consistent and user-friendly.

### Acceptance Criteria
The team must agree on the prototype created in Figma.

**Comment by tobilobasalawu** [comment]
https://www.figma.com/design/jmBq0jRIWWcc7cbwmpeYXu/SUPPORTLY---AI-CUSTOMER-SUPPORT-CONCEPT?node-id=0-1&t=ZkVzopEPodcvabjn-1
